export { Details } from './Details'
export { Home } from './Home'
export { MovieReleases } from './Release'
export { Popular } from './Popular'
export { Search } from './Search'
export { Contact } from './Contact'